dist: xenial
language: python

services:
  - mysql
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install codecov

script:
  - pytest

after_success:
  - codecov

deploy:
  - provider: script
    script: bash ./docker-deploy.sh master
    on:
      branch: master

  - provider: script
    script: bash ./codker-deploy.sh dev
    on:
      branch: dev
