language: python

dist: xenial

python:
  - "3.7"

services:
  - mysql
  - docker

cache: pip

install:
  - "pip install -r requirements.txt"

script:
  - echo "skipping tests"

deploy:
  -
    provider: script
    script: "bash ./docker-deploy.sh master"
    true:
      branch: master
  -
    provider: script
    script: "bash ./codker-deploy.sh api"
    true:
      branch: api